services:
  localspeed:
    build: .
    container_name: localspeed_app
    ports:
      - 8002:80
    restart: unless-stopped
    environment:
      - WEB_CONCURRENCY=8
      - TZ=Europe/Warsaw
      # Domy≈õlne dane logowania (zmienne pobierane z .env)
      - APP_USER=${APP_USER:-admin}
      - APP_PASSWORD=${APP_PASSWORD:-admin}
    volumes:
      - ./app:/app
networks: {}