services:
  localspeed:
    build: .
    container_name: localspeed_app
    ports:
      - 8002:80
    restart: unless-stopped
    # Zwiększamy ilość workerów uvicorn, aby obsłużyć równoległe żądania
    environment:
      - WEB_CONCURRENCY=8
      - TZ=Europe/Amsterdam
    volumes:
      - ./app:/app
networks: {}
