services:
  localspeed:
    build: .
    container_name: localspeed_app
    ports:
      - 8002:80
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy  # KLUCZOWE: Czekaj aż baza będzie 'healthy'
    environment:
      #- WEB_CONCURRENCY=8
      - TZ=Europe/Warsaw
      - APP_USER=${APP_USER:-admin}
      - APP_PASSWORD=${APP_PASSWORD:-admin}
      - AUTH_ENABLED=${AUTH_ENABLED:-true}
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./app:/app
  
  db:
    image: mariadb:10.11
    container_name: localspeed_db
    restart: unless-stopped
    # Dodajemy --innodb-use-native-aio=0 aby uniknąć problemów z io_uring na niektórych kernelach
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-use-native-aio=0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Warsaw
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10   # Zwiększamy liczbę prób, bo pierwszy start inicjalizacji trwa dłużej

volumes:
  mariadb_data: